### PR TITLE
Fix: parsing URL params from request gives wrong  dict values.

### PR DESCRIPTION
**Pull request by tadams42**
In get_request_query_body_args:

```
dict(request_obj.args)
```

will not work as intended, since `request_obj.args` is ImmutableMultiDict (when method is called with flask.request as argument), and thus will give `{'x': [42]}` instead of `{'x': 42}`

It was also not caught in tests because test were not using data type identical to flask.request.args

### CODE REVIEW

**Comment by timmartin19** [comment]
Uh oh... It looks like #6 is giving this issues.  Github won't let me merge the pull request until it's resolved.  Otherwise, it looks good to me.  My bad for not doing them in order.

**Comment by tadams42** [comment]
I've resolved the conflicts, should be OK now.

**Comment by timmartin19** [comment]
So I remember now why it's not done that way, for query args it is legal to have multiple arguments with the same name.

```
http://host:port/endpoint?x=1&x=2
```

Hence why werkzeug uses a multi-dict.  It is assumed that either the application itself is responsible for unpacking the values correctly.  Ripozo includes the fields which will automatically unpack them for you.

May I ask what your issue was that brought about this pull request?  Maybe we can find a solution.

**Comment by tadams42** [comment]
Ah, I understand now... I was trying to solve the problem with `page` URL parameter. I was getting exception in from [ripozo-sqlalchemy](https://github.com/vertical-knowledge/ripozo-sqlalchemy) for something like this:

```
pagination_pk = ["2"]
# ...
# and this would give an exception
pagination_pk -= 1 
```

First I tried to fix it in  [ripozo-sqlalchemy](https://github.com/vertical-knowledge/ripozo-sqlalchemy) like this:

```
pagination_pk = int(["2"])
# ...
# and this would give an exception
pagination_pk -= 1 
```

This obviously doesn't work, so tracing it further, I figured out that I must also patch [flask-ripozo](https://github.com/vertical-knowledge/flask-ripozo) to extract correct type for URL parameter `page`, ie to get `"2"` instead of `[2]`. That's how this pull request was created.

As it turns out, not only this pull request is not needed (see: https://github.com/vertical-knowledge/ripozo-sqlalchemy/pull/6) but fix is also wrong: it doesn't preserve all values from request multidict.

I think you can close/discard this pull request, without merging. 

I'll address the remaining work in https://github.com/vertical-knowledge/ripozo-sqlalchemy/pull/6, and that will solve the original problem correctly.

thnx

**Comment by timmartin19** [comment]
That makes sense.  If you want to contribute the test update I'd be fine with that.  But it's up to you.

**Pull request closed without merging**
